GET http://localhost:8080/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJ0b20iLCJwYXNzd29yZCI6IjEyMzQ1IiwiaWF0IjoxNjc4MjU5NDI0fQ.Km1hWXOz2LmfiPAuQux7dT8crPm79r942JPIEhqPFrE
###

POST http://localhost:8080/api/login
Content-Type: application/json

{
    "username":"huong55",
    "password":"12345"
}
###

POST http://localhost:8080/api/add-user
Content-Type: application/json

{
    "username":"huong55",
    "password":"12345"
}